### ISSUE TITLE
Upload Controller fails – Encoding::UndefinedConversionError - "\xFF" from ASCII-8BIT to UTF-8:

### ISSUE THREAD

**Issue by jakubstraka** [tomasc/simple_form_attachments#3]
Getting this error for every upload

```
Started POST "/attachments" for ::1 at 2015-07-19 11:33:28 +0200
Processing by SimpleFormAttachments::UploadController#create as JSON
  Parameters: {"attachment_type"=>"AttachmentImage", "attachment_parent"=>{"name"=>"slideshow_particle", "class"=>"SlideshowParticle"}, "attachment_relation"=>{"type"=>"Mongoid::Relations::Referenced::ManyToMany", "key"=>"attachment_image_ids", "name"=>"attachment_images", "multiple"=>"true"}, "authenticity_token"=>"6rID9+hxjLwY8/JbuQbKI8fKVF5qUxXesAmVXweK5bgLnSxmiFDzKRFHGtOJczJtJGpo/cSffFEuBOw6f7W0Gw==", "attachment"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0000010bbcef10 @tempfile=#<Tempfile:/var/folders/g6/pbc73nwj4lxd_d3n2mvby1w80000gn/T/RackMultipart20150719-6478-1yj19nv.jpg>, @original_filename="4311725657_c89514586b_o.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"attachment[file]\"; filename=\"4311725657_c89514586b_o.jpg\"\r\nContent-Type: image/jpeg\r\n">}}
DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/var/folders/g6/pbc73nwj4lxd_d3n2mvby1w80000gn/T/RackMultipart20150719-6478-1yj19nv.jpg'
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.9860ms
  MOPED: 127.0.0.1:27017 INSERT       database=db_development collection=fs.chunks documents=[{"_id"=><BSON::ObjectId:0x2262436260 data=55ab6ee84a616b194e000005>, "n"=>0, "files_id"=><BSON::ObjectId:0x2262440020 data=55ab6ee84a616b194e000004>, "data"=><BSON::Binary:0x2262434960 type=generic data=0xffd8ffe000104a46...>}] flags=[]
                         COMMAND      database=db_development command={:getlasterror=>1, :w=>1} runtime: 3.1770ms
Completed 500 Internal Server Error in 28ms

Encoding::UndefinedConversionError - "\xFF" from ASCII-8BIT to UTF-8:
  bson (3.1.2) lib/bson/binary.rb:137:in `block in to_bson'
  bson (3.1.2) lib/bson/encodable.rb:81:in `encode_binary_data_with_placeholder'
  bson (3.1.2) lib/bson/binary.rb:134:in `to_bson'
  bson (3.1.2) lib/bson/hash.rb:46:in `block (2 levels) in to_bson'
  bson (3.1.2) lib/bson/hash.rb:43:in `block in to_bson'
  bson (3.1.2) lib/bson/encodable.rb:57:in `encode_with_placeholder_and_null'
  bson (3.1.2) lib/bson/hash.rb:42:in `to_bson'
  moped (2.0.6) lib/moped/protocol/message.rb:166:in `block in serialize_documents'
  moped (2.0.6) lib/moped/protocol/message.rb:165:in `serialize_documents'
  moped (2.0.6) lib/moped/protocol/message.rb:323:in `serialize'
  moped (2.0.6) lib/moped/connection.rb:171:in `block in write'
  moped (2.0.6) lib/moped/connection.rb:169:in `write'
  moped (2.0.6) lib/moped/node.rb:590:in `block (2 levels) in flush'
  moped (2.0.6) lib/moped/node.rb:182:in `block in ensure_connected'
  moped (2.0.6) lib/moped/node.rb:115:in `block in connection'
  connection_pool (2.2.0) lib/connection_pool.rb:64:in `block (2 levels) in with'
  connection_pool (2.2.0) lib/connection_pool.rb:63:in `block in with'
  connection_pool (2.2.0) lib/connection_pool.rb:60:in `with'
  moped (2.0.6) lib/moped/node.rb:114:in `connection'
  moped (2.0.6) lib/moped/node.rb:178:in `ensure_connected'
  moped (2.0.6) lib/moped/node.rb:589:in `block in flush'
  moped (2.0.6) lib/moped/node.rb:617:in `block in logging'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  moped (2.0.6) lib/moped/instrumentable.rb:31:in `instrument'
  moped (2.0.6) lib/moped/node.rb:616:in `logging'
  moped (2.0.6) lib/moped/node.rb:587:in `flush'
  moped (2.0.6) lib/moped/node.rb:358:in `pipeline'
  moped (2.0.6) lib/moped/operation/write.rb:47:in `execute'
  moped (2.0.6) lib/moped/node.rb:665:in `write'
  moped (2.0.6) lib/moped/node.rb:273:in `insert'
  moped (2.0.6) lib/moped/collection.rb:128:in `block (2 levels) in insert'
  moped (2.0.6) lib/moped/cluster.rb:249:in `block in with_primary'
  moped (2.0.6) lib/moped/node.rb:204:in `block in ensure_primary'
  moped (2.0.6) lib/moped/executable.rb:25:in `execute'
  moped (2.0.6) lib/moped/node.rb:203:in `ensure_primary'
  moped (2.0.6) lib/moped/cluster.rb:248:in `with_primary'
  moped (2.0.6) lib/moped/collection.rb:127:in `block in insert'
  moped (2.0.6) lib/moped/retryable.rb:30:in `with_retry'
  moped (2.0.6) lib/moped/collection.rb:125:in `insert'
  mongoid (4.0.2) lib/mongoid/query_cache.rb:117:in `insert_with_clear_cache'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:27:in `block in insert'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_create_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/interceptable.rb:138:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/interceptable.rb:138:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:23:in `insert'
  mongoid (4.0.2) lib/mongoid/persistable/savable.rb:23:in `save'
  mongoid (4.0.2) lib/mongoid/persistable/savable.rb:44:in `save!'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:154:in `block (2 levels) in put'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:479:in `chunking'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:147:in `block in put'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:454:in `block in reading'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:494:in `rewind'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:453:in `reading'
  mongoid-grid_fs (2.1.0) lib/mongoid/grid_fs.rb:136:in `put'
  (eval):2:in `put'
  dragonfly-mongoid_data_store (0.0.1) lib/dragonfly/mongoid_data_store.rb:29:in `block in write'
  dragonfly (1.0.10) lib/dragonfly/temp_object.rb:89:in `file'
  /Users/Jakub/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/forwardable.rb:183:in `file'
  dragonfly-mongoid_data_store (0.0.1) lib/dragonfly/mongoid_data_store.rb:28:in `write'
  dragonfly (1.0.10) lib/dragonfly/content.rb:180:in `store'
  /Users/Jakub/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/forwardable.rb:183:in `store'
  dragonfly (1.0.10) lib/dragonfly/model/attachment.rb:179:in `store_job!'
  dragonfly (1.0.10) lib/dragonfly/model/attachment.rb:77:in `save!'
  dragonfly (1.0.10) lib/dragonfly/model/instance_methods.rb:16:in `block in save_dragonfly_attachments'
  dragonfly (1.0.10) lib/dragonfly/model/instance_methods.rb:15:in `save_dragonfly_attachments'
  activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
  activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/interceptable.rb:138:in `run_callbacks'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
  mongoid (4.0.2) lib/mongoid/persistable/creatable.rb:23:in `insert'
  mongoid (4.0.2) lib/mongoid/persistable/savable.rb:23:in `save'
  simple_form_attachments (0.0.7) app/controllers/simple_form_attachments/upload_controller.rb:5:in `create'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (1.1.0) lib/rollbar/middleware/rails/show_exceptions.rb:19:in `call_with_rollbar'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/Jakub/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/Jakub/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/Jakub/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by tomasc** [comment]
jake mas verze Dragonfly & Rails?

**Comment by jakubstraka** [comment]
dragonfly (1.0.10)
rails (4.2.0)
